### ISSUE TITLE
Can't extend custom TSLint config

### ISSUE THREAD

**Issue by davidchin** [tkqubo/codeclimate-tslint#51]
I have a shared TSLint config that I use in multiple projects. i.e.:

```json
{ "extends": "@bigcommerce/tslint-config" }
```

However, this doesn't work because `@bigcommerce/tslint-config` is not available in the environment. Do you have any idea on how to extend custom TSLint config?

**Comment by wingrunr21** [comment]
We use the [prepare step](https://docs.codeclimate.com/docs/configuring-the-prepare-step) to download the config from GitHub and overwrite the one in the repo. If you have local overrides in your config you'll have to use multiple config files and have one require the other.

**Comment by arboleya** [comment]
@davidchin Were you able to get it working somehow?

@wingrunr21 Could you pls give some code sample of how you're getting around this problem?

**Comment by wingrunr21** [comment]
Well, it's basically what I said above. We do this for our [shared TSLint config](https://github.com/GuildEducationInc/tslint-config-guild)

```yaml
...
prepare:
  fetch:
    - url: 'https://raw.githubusercontent.com/GuildEducationInc/tslint-config-guild/v1.0.0/tslint.json'
      path: 'tslint.json'
...
```
